### ISSUE TITLE
Deprecate this repo in place of https://github.com/pedestal/pedestal/tree/master/samples?

### ISSUE THREAD

**Issue by danielcompton** [pedestal/samples#42]
Hi folks

I found pedestal/samples when searching for CORs info on Pedestal. It looks like these samples have moved into the main pedestal repo? If so, does it make sense to delete/deprecate this repo so people know to look at updated samples?

**Comment by ohpauleez** [comment]
Hi @danielcompton - Thanks for opening the issue!  I didn't even realize this repo still existed. I'll address the messaging in the README.

**Comment by ohpauleez** [comment]
Fixed.
